package main

import (
	"encoding/json"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

type flagInfo struct {
	Name       string `json:"name"`
	Short      string `json:"short,omitempty"`
	Type       string `json:"type"`
	Default    string `json:"default,omitempty"`
	Usage      string `json:"usage"`
	Persistent bool   `json:"persistent,omitempty"`
}

type commandInfo struct {
	Path     string     `json:"path"`
	Short    string     `json:"short,omitempty"`
	Long     string     `json:"long,omitempty"`
	Examples []string   `json:"examples,omitempty"`
	Flags    []flagInfo `json:"flags,omitempty"`
}

type exitCodeInfo struct {
	Code int    `json:"code"`
	Name string `json:"name"`
	When string `json:"when"`
}

type helpJSON struct {
	Name        string         `json:"name"`
	Version     string         `json:"version"`
	ExitCodes   []exitCodeInfo `json:"exit_codes"`
	GlobalFlags []flagInfo     `json:"global_flags"`
	Commands    []commandInfo  `json:"commands"`
}

func newHelpJSONCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "help-json",
		Short: "Emit the full CLI tree (commands, flags, examples) as JSON",
		Long: `Emit a structured description of every command, flag, and example
in the tkn-act CLI. AI agents can use this to construct correct invocations
without scraping the human-facing --help output.

The shape is documented in AGENTS.md and is part of tkn-act's public contract.`,
		Example: `  tkn-act help-json | jq '.commands[] | .path'`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			root := cmd.Root()
			out := buildHelpJSON(root)
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(out)
		},
	}
}

func buildHelpJSON(root *cobra.Command) helpJSON {
	out := helpJSON{
		Name:        root.Name(),
		Version:     version,
		ExitCodes:   exitCodeTable(),
		GlobalFlags: collectFlags(root.PersistentFlags(), true),
	}
	walkForJSON(root, &out.Commands)
	sort.Slice(out.Commands, func(i, j int) bool { return out.Commands[i].Path < out.Commands[j].Path })
	return out
}

func walkForJSON(c *cobra.Command, sink *[]commandInfo) {
	// skip the root itself and the autogenerated "help" subtree
	if c.Parent() != nil && c.Name() != "help" {
		ci := commandInfo{
			Path:  fullPath(c),
			Short: c.Short,
			Long:  strings.TrimSpace(c.Long),
		}
		if c.Example != "" {
			for _, line := range strings.Split(c.Example, "\n") {
				if t := strings.TrimSpace(line); t != "" && !strings.HasPrefix(t, "#") {
					ci.Examples = append(ci.Examples, t)
				}
			}
		}
		ci.Flags = collectFlags(c.LocalFlags(), false)
		*sink = append(*sink, ci)
	}
	for _, sub := range c.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		walkForJSON(sub, sink)
	}
}

func fullPath(c *cobra.Command) string {
	parts := []string{c.Name()}
	for p := c.Parent(); p != nil; p = p.Parent() {
		parts = append([]string{p.Name()}, parts...)
	}
	return strings.Join(parts, " ")
}

func collectFlags(fs *pflag.FlagSet, persistent bool) []flagInfo {
	var out []flagInfo
	if fs == nil {
		return out
	}
	fs.VisitAll(func(f *pflag.Flag) {
		out = append(out, flagInfo{
			Name:       f.Name,
			Short:      f.Shorthand,
			Type:       f.Value.Type(),
			Default:    f.DefValue,
			Usage:      f.Usage,
			Persistent: persistent,
		})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func exitCodeTable() []exitCodeInfo {
	return []exitCodeInfo{
		{0, "success", "command completed and (for run) the pipeline succeeded"},
		{1, "generic", "uncategorised internal error"},
		{2, "usage", "bad flag, contradictory inputs, missing required arg"},
		{3, "environment", "Docker not running, k3d/kubectl missing, cache dir not writable"},
		{4, "validate", "Tekton YAML rejected before run"},
		{5, "pipeline", "run completed but a Task or finally task failed"},
		{6, "timeout", "a Task or finally task ended due to its declared timeout"},
		{130, "cancelled", "SIGINT or SIGTERM during a run"},
	}
}
